# Generated by Django 3.0.4 on 2020-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=60, verbose_name='first name')),
                ('m_name', models.CharField(blank=True, max_length=60, verbose_name='middle_name')),
                ('l_name', models.CharField(max_length=60, verbose_name='last name')),
                ('e_name', models.CharField(blank=True, max_length=60, verbose_name='extension name')),
            ],
        ),
    ]
