# Generated by Django 3.0.4 on 2020-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200320_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentname',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth day'),
        ),
    ]
