# Generated by Django 3.0.4 on 2020-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentname_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentname',
            name='school_status',
            field=models.BooleanField(default=True, verbose_name='schooling status'),
        ),
        migrations.AlterField(
            model_name='studentname',
            name='birth_date',
            field=models.DateField(blank=True, help_text='YYYY-mm-dd', null=True, verbose_name='birth day'),
        ),
    ]
