# Generated by Django 3.0.4 on 2020-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200320_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentname',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='studentname',
            name='disability',
        ),
        migrations.AddField(
            model_name='studentname',
            name='disability',
            field=models.ManyToManyField(to='students.Disability'),
        ),
    ]
